apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wisecow-ingress 
spec:
  tls:
    - hosts:
        - localhost
      secretName: tls-secret
  rules:
    - http:
        paths:
          - path: /
            backend:
              service:
                name: wisecow-app-service
                port:
                  number: 80