apiVersion: apps/v1
kind: Service
metadata:
  name: wisecow-app-service
spec:
  selector:
    app: wisecow-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort